apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigw-deploy
  labels:
    app: apigw
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apigw
  template:
    metadata:
      labels:
        app: apigw
    spec:
      containers:
        - name: apigw
          image: apigw:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          command: ["/root/apigw/apigw"]
          envFrom:
            - configMapRef:
                name: whole-configmap

# クラスタ外部に公開
# cliからアクセスされる用
# websiteからアクセスされる用
---
apiVersion: v1
kind: Service
metadata:
  name: apigw-svc-ex
spec:
  type: NodePort
  selector:
    app: apigw
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30006
