apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigw-deploy
  labels:
    app: apigw
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apigw
  template:
    metadata:
      labels:
        app: apigw
    spec:
      containers:
        - name: apigw
          image: 192.168.1.12:5010/apigw:v1.0.8
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: whole-configmap

# クラスタ外部に公開
# cliからアクセスされる用
# websiteからアクセスされる用
---
apiVersion: v1
kind: Service
metadata:
  name: apigw-svc
spec:
  type: NodePort
  selector:
    app: apigw
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30006
