apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deploy
  labels:
    app: website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - name: website
          image: 192.168.1.12:5010/website:v1.0.3
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: whole-configmap

# クラスタ外部に公開
# userからアクセスする用
---
apiVersion: v1
kind: Service
metadata:
  name: website-svc
spec:
  type: NodePort
  selector:
    app: website
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
