apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deploy
  labels:
    app: website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - name: website
          image: website:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          command: ["/root/website/website"]
          envFrom:
            - configMapRef:
                name: whole-configmap

# クラスタ外部に公開
# userからアクセスする用
---
apiVersion: v1
kind: Service
metadata:
  name: website-svc-ex
spec:
  type: NodePort
  selector:
    app: website
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
